import { createSlice } from '@reduxjs/toolkit'

// Initial state of the user slice with predefined users
const initialState = {
  users: [
    {
      firstname: 'Mia',
      lastname: 'White',
      dateOfBirth: '04/16/1983',
      startDate: '10/25/2021',
      street: 'Magnolia Lane',
      city: 'Denver',
      state: 'NY',
      code: '80201',
      department: 'Marketing',
    },
    {
      firstname: 'Henry',
      lastname: 'Walker',
      dateOfBirth: '12/08/1979',
      startDate: '06/18/2022',
      street: 'Hickory Street',
      city: 'Washington',
      state: 'NH',
      code: '20001',
      department: 'Engineering',
    },
    {
      firstname: 'Charlotte',
      lastname: 'Green',
      dateOfBirth: '02/03/1991',
      startDate: '04/05/2022',
      street: 'Birch Avenue',
      city: 'New York',
      state: 'WV',
      code: '10001',
      department: 'Human Resources',
    },
    {
      firstname: 'Jack',
      lastname: 'Walker',
      dateOfBirth: '05/11/1984',
      startDate: '01/30/2022',
      street: 'Oak Lane',
      city: 'Los Angeles',
      state: 'VT',
      code: '90001',
      department: 'Legal',
    },
    {
      firstname: 'Aria',
      lastname: 'Lee',
      dateOfBirth: '03/06/1986',
      startDate: '07/05/2021',
      street: 'Cedar Drive',
      city: 'Chicago',
      state: 'RI',
      code: '60007',
      department: 'Sales',
    },
    {
      firstname: 'Ethan',
      lastname: 'Harris',
      dateOfBirth: '09/18/1993',
      startDate: '03/08/2022',
      street: 'Pine Street',
      city: 'Miami',
      state: 'SC',
      code: '33101',
      department: 'Marketing',
    },
    {
      firstname: 'Lily',
      lastname: 'King',
      dateOfBirth: '06/24/1978',
      startDate: '11/01/2021',
      street: 'Maple Avenue',
      city: 'Seattle',
      state: 'ND',
      code: '98101',
      department: 'Engineering',
    },
    {
      firstname: 'Jackson',
      lastname: 'Wright',
      dateOfBirth: '08/01/1995',
      startDate: '05/15/2022',
      street: 'Elm Street',
      city: 'Boston',
      state: 'MS',
      code: '02101',
      department: 'Human Resources',
    },
    {
      firstname: 'Luna',
      lastname: 'Adams',
      dateOfBirth: '01/13/1981',
      startDate: '09/22/2021',
      street: 'Spruce Street',
      city: 'Houston',
      state: 'MO',
      code: '77001',
      department: 'Legal',
    },
    {
      firstname: 'Carter',
      lastname: 'Lee',
      dateOfBirth: '07/07/1976',
      startDate: '06/10/2022',
      street: 'Chestnut Street',
      city: 'San Francisco',
      state: 'UT',
      code: '94101',
      department: 'Sales',
    },
    {
      firstname: 'Oliver',
      lastname: 'Smith',
      dateOfBirth: '09/20/1988',
      startDate: '03/12/2022',
      street: 'Cedar Avenue',
      city: 'Chicago',
      state: 'IL',
      code: '60601',
      department: 'Engineering',
    },
    {
      firstname: 'Sophia',
      lastname: 'Davis',
      dateOfBirth: '05/08/1990',
      startDate: '02/18/2022',
      street: 'Maple Street',
      city: 'Seattle',
      state: 'WA',
      code: '98101',
      department: 'Marketing',
    },
    {
      firstname: 'Logan',
      lastname: 'Anderson',
      dateOfBirth: '11/14/1985',
      startDate: '06/25/2021',
      street: 'Pine Avenue',
      city: 'New York',
      state: 'NY',
      code: '10001',
      department: 'Sales',
    },
    {
      firstname: 'Harper',
      lastname: 'Wilson',
      dateOfBirth: '07/02/1993',
      startDate: '01/08/2022',
      street: 'Elm Street',
      city: 'Los Angeles',
      state: 'CA',
      code: '90001',
      department: 'Human Resources',
    },
    {
      firstname: 'James',
      lastname: 'Thomas',
      dateOfBirth: '02/17/1979',
      startDate: '11/01/2021',
      street: 'Oak Avenue',
      city: 'Dallas',
      state: 'TX',
      code: '75201',
      department: 'Legal',
    },
    {
      firstname: 'Amelia',
      lastname: 'Brown',
      dateOfBirth: '06/05/1982',
      startDate: '10/15/2021',
      street: 'Sycamore Lane',
      city: 'San Diego',
      state: 'CA',
      code: '92101',
      department: 'Engineering',
    },
    {
      firstname: 'Daniel',
      lastname: 'Garcia',
      dateOfBirth: '04/21/1992',
      startDate: '07/05/2022',
      street: 'Hickory Street',
      city: 'San Francisco',
      state: 'CA',
      code: '94101',
      department: 'Marketing',
    },
    {
      firstname: 'Emily',
      lastname: 'Martinez',
      dateOfBirth: '12/30/1987',
      startDate: '05/20/2022',
      street: 'Chestnut Avenue',
      city: 'Houston',
      state: 'TX',
      code: '77001',
      department: 'Sales',
    },
    {
      firstname: 'Benjamin',
      lastname: 'Lopez',
      dateOfBirth: '08/14/1975',
      startDate: '04/02/2022',
      street: 'Birch Street',
      city: 'Boston',
      state: 'MA',
      code: '02101',
      department: 'Human Resources',
    },
    {
      firstname: 'Ava',
      lastname: 'Gonzalez',
      dateOfBirth: '01/06/1994',
      startDate: '08/08/2021',
      street: 'Spruce Avenue',
      city: 'Miami',
      state: 'FL',
      code: '33101',
      department: 'Legal',
    },
    {
      firstname: 'Mason',
      lastname: 'Rodriguez',
      dateOfBirth: '07/18/1980',
      startDate: '06/15/2022',
      street: 'Poplar Lane',
      city: 'Atlanta',
      state: 'GA',
      code: '30301',
      department: 'Engineering',
    },
    {
      firstname: 'Mia',
      lastname: 'Walker',
      dateOfBirth: '01/25/1986',
      startDate: '09/02/2021',
      street: 'Cedar Street',
      city: 'Chicago',
      state: 'IL',
      code: '60601',
      department: 'Marketing',
    },
    {
      firstname: 'Liam',
      lastname: 'Perez',
      dateOfBirth: '07/07/1991',
      startDate: '12/12/2021',
      street: 'Maple Avenue',
      city: 'Seattle',
      state: 'WA',
      code: '98101',
      department: 'Sales',
    },
    {
      firstname: 'Charlotte',
      lastname: 'Harris',
      dateOfBirth: '03/09/1983',
      startDate: '11/15/2021',
      street: 'Pine Street',
      city: 'New York',
      state: 'NY',
      code: '10001',
      department: 'Human Resources',
    },
    {
      firstname: 'Noah',
      lastname: 'Clark',
      dateOfBirth: '09/12/1989',
      startDate: '01/22/2022',
      street: 'Elm Avenue',
      city: 'Los Angeles',
      state: 'CA',
      code: '90001',
      department: 'Legal',
    },
    {
      firstname: 'Grace',
      lastname: 'Lewis',
      dateOfBirth: '05/27/1977',
      startDate: '10/01/2021',
      street: 'Oak Street',
      city: 'Dallas',
      state: 'TX',
      code: '75201',
      department: 'Engineering',
    },
    {
      firstname: 'Henry',
      lastname: 'Young',
      dateOfBirth: '02/11/1984',
      startDate: '09/10/2021',
      street: 'Sycamore Street',
      city: 'San Diego',
      state: 'CA',
      code: '92101',
      department: 'Marketing',
    },
    {
      firstname: 'Ella',
      lastname: 'King',
      dateOfBirth: '06/19/1996',
      startDate: '07/20/2022',
      street: 'Hickory Avenue',
      city: 'San Francisco',
      state: 'CA',
      code: '94101',
      department: 'Sales',
    },
    {
      firstname: 'Owen',
      lastname: 'Scott',
      dateOfBirth: '12/23/1981',
      startDate: '05/25/2022',
      street: 'Chestnut Street',
      city: 'Houston',
      state: 'TX',
      code: '77001',
      department: 'Human Resources',
    },
    {
      firstname: 'Stella',
      lastname: 'Green',
      dateOfBirth: '08/07/1976',
      startDate: '04/10/2022',
      street: 'Birch Avenue',
      city: 'Boston',
      state: 'MA',
      code: '02101',
      department: 'Legal',
    },
    {
      firstname: 'William',
      lastname: 'Adams',
      dateOfBirth: '02/15/1982',
      startDate: '08/18/2021',
      street: 'Spruce Street',
      city: 'Miami',
      state: 'FL',
      code: '33101',
      department: 'Engineering',
    },
    {
      firstname: 'Luna',
      lastname: 'Campbell',
      dateOfBirth: '01/28/1988',
      startDate: '06/05/2022',
      street: 'Poplar Avenue',
      city: 'Atlanta',
      state: 'GA',
      code: '30301',
      department: 'Marketing',
    },
    {
      firstname: 'Michael',
      lastname: 'Rivera',
      dateOfBirth: '07/13/1993',
      startDate: '09/22/2021',
      street: 'Cedar Lane',
      city: 'Chicago',
      state: 'IL',
      code: '60601',
      department: 'Sales',
    },
    {
      firstname: 'Victoria',
      lastname: 'Cook',
      dateOfBirth: '03/03/1985',
      startDate: '11/25/2021',
      street: 'Maple Lane',
      city: 'Seattle',
      state: 'WA',
      code: '98101',
      department: 'Human Resources',
    },
    {
      firstname: 'Alexander',
      lastname: 'Morgan',
      dateOfBirth: '09/28/1990',
      startDate: '02/02/2022',
      street: 'Pine Lane',
      city: 'New York',
      state: 'NY',
      code: '10001',
      department: 'Legal',
    },
    {
      firstname: 'Sofia',
      lastname: 'Lee',
      dateOfBirth: '04/11/1987',
      startDate: '11/08/2021',
      street: 'Elm Lane',
      city: 'Los Angeles',
      state: 'CA',
      code: '90001',
      department: 'Engineering',
    },
    {
      firstname: 'Matthew',
      lastname: 'Reed',
      dateOfBirth: '06/09/1981',
      startDate: '10/15/2021',
      street: 'Oak Street',
      city: 'Dallas',
      state: 'TX',
      code: '75201',
      department: 'Marketing',
    },
    {
      firstname: 'Avery',
      lastname: 'Parker',
      dateOfBirth: '01/07/1995',
      startDate: '09/05/2022',
      street: 'Sycamore Avenue',
      city: 'San Diego',
      state: 'CA',
      code: '92101',
      department: 'Sales',
    },
    {
      firstname: 'Scarlett',
      lastname: 'Morris',
      dateOfBirth: '12/26/1988',
      startDate: '05/22/2022',
      street: 'Hickory Lane',
      city: 'San Francisco',
      state: 'CA',
      code: '94101',
      department: 'Human Resources',
    },
    {
      firstname: 'Joseph',
      lastname: 'Turner',
      dateOfBirth: '07/29/1978',
      startDate: '04/15/2022',
      street: 'Chestnut Lane',
      city: 'Houston',
      state: 'TX',
      code: '77001',
      department: 'Legal',
    },
    {
      firstname: 'Penelope',
      lastname: 'Bailey',
      dateOfBirth: '08/30/1979',
      startDate: '03/02/2022',
      street: 'Birch Lane',
      city: 'Boston',
      state: 'MA',
      code: '02101',
      department: 'Engineering',
    },
    {
      firstname: 'Leo',
      lastname: 'Cooper',
      dateOfBirth: '02/20/1993',
      startDate: '08/28/2021',
      street: 'Spruce Street',
      city: 'Miami',
      state: 'FL',
      code: '33101',
      department: 'Marketing',
    },
  ],
}

/**
 * Redux slice for managing user data.
 * It contains state and reducers to handle user-related actions in the application.
 */
export const userSlice = createSlice({
  name: 'user',
  initialState,
  reducers: {
    /**
     * Reducer for adding a new user.
     * Appends a user object to the existing users array in the state.
     *
     * @param {object} state - The current state of the user slice.
     * @param {object} action - The action object containing payload with user data.
     */
    addUser: (state, action) => {
      state.users.push(action.payload)
    },
  },
})

export const { addUser } = userSlice.actions

export default userSlice.reducer
